import os
from dotenv import load_dotenv

load_dotenv()

FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY")
ALPHA_VANTAGE_API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY")
FRED_API_KEY = os.getenv("FRED_API_KEY") 
NASDAQ_DATA_LINK_API_KEY = os.getenv("NASDAQ_DATA_LINK_API_KEY") 

DB_NAME = "data/market_data.db"

LOG_FILE = "logs/financial_system.log"
LOG_LEVEL = "INFO"

DEFAULT_ASSETS_MONITOR = ["AAPL", "MSFT", "GOOGL", "NVDA", "PETR4.SA", "VALE3.SA", "ITUB4.SA"]
DEFAULT_INDICES_MONITOR = ["^BVSP", "^GSPC", "^IXIC"]

CACHE_EXPIRATION_SGS = 24 * 60 * 60  
CACHE_EXPIRATION_PTAX = 24 * 60 * 60  
CACHE_EXPIRATION_FINNHUB_QUOTE = 15 * 60 
CACHE_EXPIRATION_YFINANCE_HISTORY = 4 * 60 * 60 
CACHE_EXPIRATION_ALPHA_VANTAGE_TIMESERIES = 24 * 60 * 60 
CACHE_EXPIRATION_INVESTPY = 4 * 60 * 60 
CACHE_EXPIRATION_FRED = 24 * 60 * 60  
CACHE_EXPIRATION_NASDAQ = 24 * 60 * 60 

LSTM_LOOKBACK_PERIOD = 60
LSTM_TRAIN_TEST_SPLIT = 0.7
LSTM_EPOCHS = 50
LSTM_BATCH_SIZE = 32

PROPHET_FORECAST_PERIODS = 30 
PROPHET_DEFAULT_CONFIGS = {
    'daily_seasonality': False,
    'weekly_seasonality': True,
    'yearly_seasonality': True,
    'seasonality_mode': 'additive',
}

BCB_SERIES_IPCA = 433
BCB_SERIES_SELIC = 432
BCB_SERIES_USD_BRL_EXCHANGE = 1

INVESTPY_COUNTRY_MAP = {
    ".SA": "brazil",
    "": "united states" 
}

DEFAULT_HISTORICAL_PERIOD = "1y"
DEFAULT_INDICATORS_VIEW = ["SMA_21", "EMA_21", "MACD_Hist", "RSI_14"]
ALERT_CHECK_INTERVAL_SECONDS = 60 * 5 
DEFAULT_EXPORT_PATH = "exports/"
DEFAULT_USER_ID_PREFERENCES = 0 